### ISSUE TITLE
Example with SVG

### ISSUE THREAD

**Issue by TehShrike** [ldd/fantasy-map-generator#2]
I'm a canvas noob - could you add an example to the readme showing how to create an SVG element that I could pass in to `drawMap`?

I tried just tossing `<svg id="map"></svg>` into my body, but passing the element in to `drawMap` resulted in

```
Uncaught TypeError: svg.selectAll is not a function
    at drawPaths (view.js:126)
    at Object.drawMap (visualize.js:20)
    at (index):16
```

which I'm pretty sure is the result of me not knowing what I'm doing.

**Comment by ldd** [comment]
in the browser, with d3:
d3.select('#map');

you are right that the documentation is terse.

**Comment by TehShrike** [comment]
aah, that makes sense, I had assumed that d3 was just used internally. 👍
