### ISSUE TITLE
Publish web build to npm

### ISSUE THREAD

**Issue by TehShrike** [ldd/fantasy-map-generator#3]
Right now npm contains the node build (`main.js`) but not the web or web worker builds of the module.  Are you assuming this module will be bundler-only?  If so, you could drop the webpack scripts for the other builds to simplify things.

**Comment by ldd** [comment]
you are right, I initially wrote a reply to say that it wasn't needed, but I've done plenty of `npm install` commands just to get minified files anyways. I'm adding the web build and worker build to npm.

ps: the web build is available in the branch `gh-pages`

**Comment by ldd** [comment]
I think this is fixed, see 727792b20dcb24763c585ed4bfa516dabc107078

**Comment by TehShrike** [comment]
Sweet, looks like it's out on npm!

**Comment by TehShrike** [comment]
Oh and hey, you should link to https://ldd.github.io/fantasy-map-generator/ in the repo description!
